#pragma once

#include "pch.h"

namespace Doodle
{

enum class KeyCode
{
    Space = 32,
    Apostrophe = 39, /* ' */
    Comma = 44,      /* , */
    Minus = 45,      /* - */
    Period = 46,     /* . */
    Slash = 47,      /* / */
    Alpha0 = 48,
    Alpha1 = 49,
    Alpha2 = 50,
    Alpha3 = 51,
    Alpha4 = 52,
    Alpha5 = 53,
    Alpha6 = 54,
    Alpha7 = 55,
    Alpha8 = 56,
    Alpha9 = 57,
    Semicolon = 59, /* ; */
    Equal = 61,     /* = */
    A = 65,
    B = 66,
    C = 67,
    D = 68,
    E = 69,
    F = 70,
    G = 71,
    H = 72,
    I = 73,
    J = 74,
    K = 75,
    L = 76,
    M = 77,
    N = 78,
    O = 79,
    P = 80,
    Q = 81,
    R = 82,
    S = 83,
    T = 84,
    U = 85,
    V = 86,
    W = 87,
    X = 88,
    Y = 89,
    Z = 90,
    LeftBracket = 91,  /* [ */
    Backslash = 92,    /* \ */
    RightBracket = 93, /* ] */
    GraveAccent = 96,  /* ` */
    World1 = 161,      /* non-US #1 */
    World2 = 162,      /* non-US #2 */

    /* Function keys */
    Escape = 256,
    Enter = 257,
    Tab = 258,
    Backspace = 259,
    Insert = 260,
    Delete = 261,
    Right = 262,
    Left = 263,
    Down = 264,
    Up = 265,
    PageUp = 266,
    PageDown = 267,
    Home = 268,
    End = 269,
    CapsLock = 280,
    ScrollLock = 281,
    NumLock = 282,
    PrintScreen = 283,
    Pause = 284,
    F1 = 290,
    F2 = 291,
    F3 = 292,
    F4 = 293,
    F5 = 294,
    F6 = 295,
    F7 = 296,
    F8 = 297,
    F9 = 298,
    F10 = 299,
    F11 = 300,
    F12 = 301,
    F13 = 302,
    F14 = 303,
    F15 = 304,
    F16 = 305,
    F17 = 306,
    F18 = 307,
    F19 = 308,
    F20 = 309,
    F21 = 310,
    F22 = 311,
    F23 = 312,
    F24 = 313,
    F25 = 314,
    Keypad0 = 320,
    Keypad1 = 321,
    Keypad2 = 322,
    Keypad3 = 323,
    Keypad4 = 324,
    Keypad5 = 325,
    Keypad6 = 326,
    Keypad7 = 327,
    Keypad8 = 328,
    Keypad9 = 329,
    KeypadDecimal = 330,
    KeypadDivide = 331,
    KeypadMultiply = 332,
    KeypadSubtract = 333,
    KeypadAdd = 334,
    KeypadEnter = 335,
    KeypadEqual = 336,
    LeftShift = 340,
    LeftControl = 341,
    LeftAlt = 342,
    LeftSuper = 343,
    RightShift = 344,
    RightControl = 345,
    RightAlt = 346,
    RightSuper = 347,
    Menu = 348
};

enum class KeyState
{
    None = -1,
    Pressed,
    Held,
    Released
};

static KeyCode GetKeyCode(std::string name)
{

    // 名字到 KeyCode 的映射
    static std::unordered_map<std::string, KeyCode> s_KeyCodeMap = {{"Space", KeyCode::Space},
                                                                    {"Apostrophe", KeyCode::Apostrophe},
                                                                    {"Comma", KeyCode::Comma},
                                                                    {"Minus", KeyCode::Minus},
                                                                    {"Period", KeyCode::Period},
                                                                    {"Slash", KeyCode::Slash},
                                                                    {"Alpha0", KeyCode::Alpha0},
                                                                    {"Alpha1", KeyCode::Alpha1},
                                                                    {"Alpha2", KeyCode::Alpha2},
                                                                    {"Alpha3", KeyCode::Alpha3},
                                                                    {"Alpha4", KeyCode::Alpha4},
                                                                    {"Alpha5", KeyCode::Alpha5},
                                                                    {"Alpha6", KeyCode::Alpha6},
                                                                    {"Alpha7", KeyCode::Alpha7},
                                                                    {"Alpha8", KeyCode::Alpha8},
                                                                    {"Alpha9", KeyCode::Alpha9},
                                                                    {"Semicolon", KeyCode::Semicolon},
                                                                    {"Equal", KeyCode::Equal},
                                                                    {"A", KeyCode::A},
                                                                    {"B", KeyCode::B},
                                                                    {"C", KeyCode::C},
                                                                    {"D", KeyCode::D},
                                                                    {"E", KeyCode::E},
                                                                    {"F", KeyCode::F},
                                                                    {"G", KeyCode::G},
                                                                    {"H", KeyCode::H},
                                                                    {"I", KeyCode::I},
                                                                    {"J", KeyCode::J},
                                                                    {"K", KeyCode::K},
                                                                    {"L", KeyCode::L},
                                                                    {"M", KeyCode::M},
                                                                    {"N", KeyCode::N},
                                                                    {"O", KeyCode::O},
                                                                    {"P", KeyCode::P},
                                                                    {"Q", KeyCode::Q},
                                                                    {"R", KeyCode::R},
                                                                    {"S", KeyCode::S},
                                                                    {"T", KeyCode::T},
                                                                    {"U", KeyCode::U},
                                                                    {"V", KeyCode::V},
                                                                    {"W", KeyCode::W},
                                                                    {"X", KeyCode::X},
                                                                    {"Y", KeyCode::Y},
                                                                    {"Z", KeyCode::Z},
                                                                    {"LeftBracket", KeyCode::LeftBracket},
                                                                    {"Backslash", KeyCode::Backslash},
                                                                    {"RightBracket", KeyCode::RightBracket},
                                                                    {"GraveAccent", KeyCode::GraveAccent},
                                                                    {"World1", KeyCode::World1},
                                                                    {"World2", KeyCode::World2},
                                                                    {"Escape", KeyCode::Escape},
                                                                    {"Enter", KeyCode::Enter},
                                                                    {"Tab", KeyCode::Tab},
                                                                    {"Backspace", KeyCode::Backspace},
                                                                    {"Insert", KeyCode::Insert},
                                                                    {"Delete", KeyCode::Delete},
                                                                    {"Right", KeyCode::Right},
                                                                    {"Left", KeyCode::Left},
                                                                    {"Down", KeyCode::Down},
                                                                    {"Up", KeyCode::Up},
                                                                    {"PageUp", KeyCode::PageUp},
                                                                    {"PageDown", KeyCode::PageDown},
                                                                    {"Home", KeyCode::Home},
                                                                    {"End", KeyCode::End},
                                                                    {"CapsLock", KeyCode::CapsLock},
                                                                    {"ScrollLock", KeyCode::ScrollLock},
                                                                    {"NumLock", KeyCode::NumLock},
                                                                    {"PrintScreen", KeyCode::PrintScreen},
                                                                    {"Pause", KeyCode::Pause},
                                                                    {"F1", KeyCode::F1},
                                                                    {"F2", KeyCode::F2},
                                                                    {"F3", KeyCode::F3},
                                                                    {"F4", KeyCode::F4},
                                                                    {"F5", KeyCode::F5},
                                                                    {"F6", KeyCode::F6},
                                                                    {"F7", KeyCode::F7},
                                                                    {"F8", KeyCode::F8},
                                                                    {"F9", KeyCode::F9},
                                                                    {"F10", KeyCode::F10},
                                                                    {"F11", KeyCode::F11},
                                                                    {"F12", KeyCode::F12},
                                                                    {"F13", KeyCode::F13},
                                                                    {"F14", KeyCode::F14},
                                                                    {"F15", KeyCode::F15},
                                                                    {"F16", KeyCode::F16},
                                                                    {"F17", KeyCode::F17},
                                                                    {"F18", KeyCode::F18},
                                                                    {"F19", KeyCode::F19},
                                                                    {"F20", KeyCode::F20},
                                                                    {"F21", KeyCode::F21},
                                                                    {"F22", KeyCode::F22},
                                                                    {"F23", KeyCode::F23},
                                                                    {"F24", KeyCode::F24},
                                                                    {"F25", KeyCode::F25},
                                                                    {"Keypad0", KeyCode::Keypad0},
                                                                    {"Keypad1", KeyCode::Keypad1},
                                                                    {"Keypad2", KeyCode::Keypad2},
                                                                    {"Keypad3", KeyCode::Keypad3},
                                                                    {"Keypad4", KeyCode::Keypad4},
                                                                    {"Keypad5", KeyCode::Keypad5},
                                                                    {"Keypad6", KeyCode::Keypad6},
                                                                    {"Keypad7", KeyCode::Keypad7},
                                                                    {"Keypad8", KeyCode::Keypad8},
                                                                    {"Keypad9", KeyCode::Keypad9},
                                                                    {"KeypadDecimal", KeyCode::KeypadDecimal},
                                                                    {"KeypadDivide", KeyCode::KeypadDivide},
                                                                    {"KeypadMultiply", KeyCode::KeypadMultiply},
                                                                    {"KeypadSubtract", KeyCode::KeypadSubtract},
                                                                    {"KeypadAdd", KeyCode::KeypadAdd},
                                                                    {"KeypadEnter", KeyCode::KeypadEnter},
                                                                    {"KeypadEqual", KeyCode::KeypadEqual},
                                                                    {"LeftShift", KeyCode::LeftShift},
                                                                    {"LeftControl", KeyCode::LeftControl},
                                                                    {"LeftAlt", KeyCode::LeftAlt},
                                                                    {"LeftSuper", KeyCode::LeftSuper},
                                                                    {"RightShift", KeyCode::RightShift},
                                                                    {"RightControl", KeyCode::RightControl},
                                                                    {"RightAlt", KeyCode::RightAlt},
                                                                    {"RightSuper", KeyCode::RightSuper},
                                                                    {"Menu", KeyCode::Menu}};
    return s_KeyCodeMap[name];
}

} // namespace Doodle
